name: Build Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@vv
        with:
          go-version: '1.21'

      - name: Install Fyne CLI
        run: go get fyne.io/fyne/v2/cmd/fyne

      - name: Create Subdirectory
        run: |
          mkdir eveSonarWindows
          mkdir eveSonarMac
          mkdir eveSonarLinux

      - name: Build Release
        run: |
          go build -o eveSonar
          fyne package -os windows -icon icon.png -output eveSonarWindows/eveSonar
          fyne package -os darwin -icon icon.png -output eveSonarMac/eveSonar
          fyne package -os linux -icon icon.png -output eveSonarLinux/eveSonar

      - name: Copy Files to Subdirectory
        run: |
          cp eveSonar/eveSolarSystems/tracker.db eveSonarWindows/eveSolarSystems
          cp eveSonar/eveSolarSystems/eveSolarSystems.csv eveSonarWindows/eveSolarSystems
          cp eveSonar/eveSolarSystems/tracker.db eveSonarMac/eveSolarSystems
          cp eveSonar/eveSolarSystems/eveSolarSystems.csv eveSonarMac/eveSolarSystems
          cp eveSonar/eveSolarSystems/tracker.db eveSonarLinux/eveSolarSystems
          cp eveSonar/eveSolarSystems/eveSolarSystems.csv eveSonarLinux/eveSolarSystems

      - name: Create ZIP Archive
        run: |
          zip -r eveSonarWindows.zip eveSonarWindows
          zip -r eveSonarMac.zip eveSonarMac
          zip -r eveSonarLinux.zip eveSonarLinux

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            eveSonarWindows1.0.${{GITHUB_RUN_NUMBER}}.zip
            eveSonarMac1.0.${{GITHUB_RUN_NUMBER}}.zip
            eveSonarLinux1.0.${{GITHUB_RUN_NUMBER}}.zip