name: Build Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.21']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Install Fyne CLI
        run: | 
          go install fyne.io/fyne/v2/cmd/fyne@latest
          fyne version

      - name: Build
        run: fyne package -icon icon.ico

      - name: copy and zip files Windows
        run: |
          mkdir Eve-Sonar
          mkdir Eve-Sonar\eveSolarSystems
          mv Eve-Sonar.exe ./Eve-Sonar
          mv eveSolarSystems/tracker.db ./Eve-Sonar/eveSolarSystems
          mv eveSolarSystems/eveSolarSystems.csv ./Eve-Sonar/eveSolarSystems
          powershell Compress-Archive -Path Eve-Sonar -DestinationPath Eve-Sonar.zip
          dir
        if: ${{ runner.os == 'Windows' }}

      - name: copy and zip files Linux
        run: |
          mkdir Eve-Sonar
          mkdir Eve-Sonar/eveSolarSystems
          move Eve-Sonar.exe C:\Eve-Sonar
          move eveSolarSystems\tracker.db C:\Eve-Sonar\eveSolarSystems
          move eveSolarSystems\eveSolarSystems.csv C:\Eve-Sonar\eveSolarSystems
          zip Eve-Sonar.zip Eve-Sonar
          ls -a
        if: ${{ runner.os == 'Linux' }}

      - name: check files for Mac
        run: ls -a
        if: ${{ runner.os == 'macOS' }}

      - name: Upload Go build results linux
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS'}}
        with:
          name: eve-sonar-linux
          path: Eve-Sonar.zip

      - name: Upload Go build results windows
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          name: eve-sonar-Windows
          path: Eve-Sonar.zip

      - name: Upload Go build results macos
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'macOS' }}
        with:
          name: eve-sonar-macOS
          path: eve-sonar