name: Build Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Install Fyne CLI
        run: | 
          go install fyne.io/fyne/v2/cmd/fyne@latest
          fyne version

      - name: Create Subdirectory
        run: |
          mkdir eveSonarWindows
          mkdir eveSonarMac
          mkdir eveSonarLinux

      - name: Build Release
        run: |
          go build -o github.com/sythe7448/Eve-Sonar
          fyne package -os windows -icon icon.ico
          fyne package -os darwin -icon icon.ico
          fyne package -os linux -icon icon.ico

      - name: Copy Files to Subdirectory
        run: |
          cp Eve-Sonar/Eve-Sonar.exe eveSonarWindows
          cp Eve-Sonar/eveSolarSystems/tracker.db eveSonarWindows/eveSolarSystems
          cp Eve-Sonar/eveSolarSystems/eveSolarSystems.csv eveSonarWindows/eveSolarSystems
          cp Eve-Sonar/Eve-Sonar.app eveSonarMac
          cp Eve-Sonar/eveSolarSystems/tracker.db eveSonarMac/eveSolarSystems
          cp Eve-Sonar/eveSolarSystems/eveSolarSystems.csv eveSonarMac/eveSolarSystems
          cp Eve-Sonar/Eve-Sonar.tar.gz eveSonarLinux
          cp Eve-Sonar/eveSolarSystems/tracker.db eveSonarLinux/eveSolarSystems
          cp Eve-Sonar/eveSolarSystems/eveSolarSystems.csv eveSonarLinux/eveSolarSystems

      - name: Create ZIP Archive
        run: |
          zip -r eveSonarWindows.zip eveSonarWindows
          zip -r eveSonarMac.zip eveSonarMac
          zip -r eveSonarLinux.zip eveSonarLinux

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            eveSonarWindows1.0.${{ github.run_number }}.zip
            eveSonarMac1.0.${{ github.run_number }}.zip
            eveSonarLinux1.0.${{ github.run_number }}.zip