name: Build Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.21']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Install Fyne CLI
        run: | 
          go install fyne.io/fyne/v2/cmd/fyne@latest
          fyne version

      - name: Build
        run: fyne package -icon icon.ico

      - name: copy files to release dir Windows
        run: |
          mkdir Eve-Sonar
          mkdir Eve-Sonar\eveSolarSystems
          move Eve-Sonar.exe Eve-Sonar\
          move eveSolarSystems\tracker.db Eve-Sonar\eveSolarSystems\
          move eveSolarSystems\eveSolarSystems.csv Eve-Sonar\eveSolarSystems\
        if: ${{ runner.os == 'Windows' }}

      - name: copy files to release dir Linux
        run: |
          mkdir Eve-Sonar
          mkdir Eve-Sonar/eveSolarSystems
          mv Eve-Sonar.tar.xz ./Eve-Sonar
          mv eveSolarSystems/tracker.db ./Eve-Sonar/eveSolarSystems
          mv eveSolarSystems/eveSolarSystems.csv ./Eve-Sonar/eveSolarSystems
        if: ${{ runner.os == 'Linux' }}

      - name: copy files to release dir Mac
        run: |
          mkdir Eve-Sonar
          mkdir Eve-Sonar/eveSolarSystems
          mv Eve-Sonar.app ./Eve-Sonar
          mv eveSolarSystems/tracker.db ./Eve-Sonar/eveSolarSystems
          mv eveSolarSystems/eveSolarSystems.csv ./Eve-Sonar/eveSolarSystems
          zip -r Eve-Sonar.zip Eve-Sonar
        if: ${{ runner.os == 'macOS' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Eve-Sonar-${{ runner.os }}
          path: Eve-Sonar

  wait-for-all:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download linux version
        uses: actions/download-artifact@v3
        with:
          name: Eve-Sonar-Linux

      - name: Download macOS version
        uses: actions/download-artifact@v3
        with:
          name: Eve-Sonar-macOS

      - name: Download linux version
        uses: actions/download-artifact@v3
        with:
          name: Eve-Sonar-Windows

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Eve-Sonar-Linux.zip
            Eve-Sonar-macOS.zip
            Eve-Sonar-Windows.zip
          tag_name: Eve-Sonar/v1.0.${{ github.run_number }}
          release_name: Release ${{ runner.os }} v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}